# Config written on Fri Nov 13 00:58:04 +0100 CET 2020
query:
  interval_seconds: 30s
teamspeak:
  host: 127.0.0.1
  port: 10011
  user: admin
  password: admin
  virtual_server_id: 1
neo4j:
  uri: bolt://127.0.0.1:7687
  user: admin
  password: admin
  encrypted: false
